// Generated by `gemma-4-26B-A4B-it-UD-Q6_K_XL`, based on SplitMix64.

/// Takes three integers and returns a "random" integer between 0 and 10,000.
/// This uses a bit-mixing hash to ensure that small changes in input
/// result in large changes in output.
pub fn prng(x: i32, y: i32, cycles: u32) -> u32 {
    // 1. Combine the three inputs into a single u64 state
    // We shift x and y to ensure they occupy different bit positions
    let mut state: u64 = (x as u64) << 32 | (y as u64);
    state ^= cycles as u64;

    // 2. Apply a bit-mixer (SplitMix64 style)
    // This "scrambles" the bits so there is no linear pattern.
    // Using wrapping operations is crucial in Rust to avoid panics in debug mode.
    state = state.wrapping_add(0x9E3779B97F4A7C15);
    state = (state ^ (state >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
    state = (state ^ (state >> 27)).wrapping_mul(0x94D049BB133111EB);
    state = state ^ (state >> 31);

    // 3. Map to the desired range [0, 9999]
    // 10000 is used because % is exclusive of the divisor
    (state % 10000) as u32
}